# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65c4f79061dbafaeeb1cddea9d4c0cd302ecad61ccf07adc1951895c185925c0d819b68047723d30da0000ec22f18820667e302f6c1b9ef9d8b68eec0150ba42

test:
  secret_key_base: 9d20fe4e86add289fae7af75dedf300a0de504bfc3e6f65c830f9786cb42b8dd0666be21aa3e1028fa28e8b82ba6c0acd32b12fd715dbc493265704008304c6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
